Add shell script for pulling down the BPFd source files from the BPFd…
joelagnel/bcc pull request #10
Opened 2018-03-15 01:38 UTC by jcanseco

… repo

This allows us to synchronize the BPFd source files found in BCC with
those found in the original BPFd repo.

Signed-off-by: Jazel Canseco <jcanseco@google.com>

2018-03-19 23:40 UTC, joelagnel requested changes

2018-03-19 23:40 UTC, joelagnel commented on src/cc/bpfd/update_bpfd_sources.sh
> +
Add code here to cd into the directory where the script lives, so that the script can be run from any directory.

You can get the path with something like:
```
SCRIPT_PATH=`dirname "$0"`
SCRIPT_PATH=`( cd "$MY_PATH" && pwd )`
```

2018-03-21 18:32 UTC, jcanseco commented on src/cc/bpfd/update_bpfd_sources.sh
> +
Done.

2018-03-21 18:33 UTC, jcanseco commented
Made the requested changes. PTAL.

I made it so that the script will still work regardless of where it is invoked from, and regardless of where it is placed (so that we don't need to worry about it breaking if it the script is moved elsewhere).

2018-03-26 21:04 UTC, merged