Add support for remote target devices via BPFd
joelagnel/bcc pull request #17
Opened 2018-04-07 00:50 UTC by jcanseco

TODO(jcanseco): Write up a description on Monday

2018-04-07 01:23 UTC, joelagnel requested changes
First wave of comments.

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +
drop new line

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +
drop new line

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +            fns = BPF._libremote.available_filter_functions(TRACEFS)
This seems wrong, if upstream wants `kallsyms`, then BPFd should give it kallsyms. This wont fly because you're making upsteam's behavior different from BPFd and is a red flag for reviewers

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +            res = BPF._libremote.bpf_close_perf_event_fd(self.kprobe_fds[ev_name])
I feel there's a lot of this pattern in this file:
```
if (remote)
  do this;
else
  do that;
```
This was Ok for prototype but wont look very nice to upstream. Can you instead do something like:
Define a static function bpf_close_perf_event_fd in the BPF class itself, and then let *that* decide what to call. Basically don't make the decision itself from here.
Also in that function you could do things like:
```
def bpf_close_perf_event_fd(fds)
   if BPF._libremote:
       return BPF._libremote.bpf_close_perf_event_fd(self.kprobe_fds[ev_name])

    return lib.bpf_close_perf_event_fd(self.kprobe_fds[ev_name])
```
Basically, the early return technique avoids the "else" completely.

Can you make that happen?

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +            res = lib.bpf_close_perf_event_fd(self.tracepoint_fds[tp])
same pattern here

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/__init__.py
> +
kill unwanted useless new line

2018-04-07 01:23 UTC, joelagnel commented on src/python/bcc/remote/libremote.py
> +
just 1 new line, not 2

2018-04-07 01:25 UTC, joelagnel commented on src/cc/bpfd/base64.c
> +
Can you change this header to Apache license, and give credit to Freecode in the license text?

2018-04-09 18:23 UTC, jcanseco commented on src/python/bcc/__init__.py
> +
Done.

2018-04-09 18:23 UTC, jcanseco commented on src/python/bcc/__init__.py
> +
Done.

2018-04-09 18:23 UTC, jcanseco commented on src/python/bcc/__init__.py
> +
I think it might be better to keep this newline here since it visually separates the block concerned with the call to `bpf_close_perf_event_fd()` and the block concerned with `bpf_detach_tracepoint()`.

2018-04-09 18:23 UTC, jcanseco commented on src/python/bcc/remote/libremote.py
> +
Done.

2018-04-09 18:23 UTC, jcanseco commented on src/python/bcc/__init__.py
> +            fns = BPF._libremote.available_filter_functions(TRACEFS)
Done.

2018-04-09 18:24 UTC, jcanseco commented on src/python/bcc/__init__.py
> +            fns = BPF._libremote.available_filter_functions(TRACEFS)
I also killed `libremote.available_filter_functions()` and the `GET_AVAILABLE_FILTER_FUNCTIONS` command in BPFd since no one else was using them.

2018-04-09 19:51 UTC, joelagnel commented on src/python/bcc/__init__.py
> +
Ok should be fine.

2018-04-09 20:28 UTC, jcanseco commented on src/python/bcc/__init__.py
> +            res = BPF._libremote.bpf_close_perf_event_fd(self.kprobe_fds[ev_name])
Done.

2018-04-09 20:28 UTC, jcanseco commented on src/python/bcc/__init__.py
> +            res = lib.bpf_close_perf_event_fd(self.tracepoint_fds[tp])
Done.

2018-04-09 20:32 UTC, jcanseco commented on src/cc/bpfd/base64.c
> +
Done. 

I don't have much experience with licenses so let me know if I still need to make changes here.

2018-04-10 23:26 UTC, jcanseco commented
Closing this PR now that we've made a [PR on the original BCC repository](https://github.com/iovisor/bcc/pull/1675).

2018-04-10 23:26 UTC, closed without merging